### ISSUE TITLE
Can't install ioLabs

### ISSUE THREAD

**Issue by orenpapers** [ioLab/python-ioLabs#3]
I use python3.6 in anaconda envriment and trying to install:
`pip install iolabs
`But get the error:

> Collecting iolabs
>   Using cached https://files.pythonhosted.org/packages/5c/f9/f8ae6a67294b48d09d0e1e5c69dad6bf6fd29abd0d51e0ff6034c4ef750a/ioLabs-3.2.tar.gz
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/private/var/folders/39/88clnp910zlg54lrgy0d7qm40000gn/T/pip-install-653z6aow/iolabs/setup.py", line 8, in <module>
>         import ioLabs
>       File "/private/var/folders/39/88clnp910zlg54lrgy0d7qm40000gn/T/pip-install-653z6aow/iolabs/ioLabs.py", line 979
>         print "USBBox connected"
>                                ^
>     SyntaxError: Missing parentheses in call to 'print'. Did you mean print("USBBox connected")?
> 
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/39/88clnp910zlg54lrgy0d7qm40000gn/T/pip-install-653z6aow/iolabs/

Any ideas?

**Comment by peircej** [comment]
The iolabs lib hasn't been updated for Python3. I could try and convert it using an automated process (python-futurize) but I wouldn't be able to test it as I don't personally have one of these boxes and I don't believe they've been made for a number of years

**Comment by orenpapers** [comment]
@peircej OK thanks, please notice it is still in the dependencies section here:

> https://www.psychopy.org/installation.html#manual-install
